/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import model.Conges;
import implementation.CongeImplement;
import implementation.Connect;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hedia
 */
public class conge extends javax.swing.JFrame {

    /**
     * Creates new form conge
     */
    public conge() {
 initComponents();
 remplircombo ();
 afficher();
ajouter.setEnabled(true);
modifier.setEnabled(false);
supprimer.setEnabled(false);
id_cong.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comb1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        zt_duree = new javax.swing.JTextField();
        zt_deb = new javax.swing.JTextField();
        r2 = new javax.swing.JRadioButton();
        r1 = new javax.swing.JRadioButton();
        demandeur = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_conge = new javax.swing.JTable();
        modifier = new javax.swing.JButton();
        button1 = new java.awt.Button();
        ajouter = new javax.swing.JButton();
        supprimer = new javax.swing.JButton();
        id_cong = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("gestion des conges");

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Gestion des conges");

        jLabel2.setText("Demandeur                :");

        jLabel3.setText("Durée                         :");

        jLabel4.setText("Debut                         :");

        jLabel5.setText("Type                           :");

        comb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "anuuel", "maladie", "autre" }));

        jLabel6.setText("Etat                             :");

        zt_deb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zt_debActionPerformed(evt);
            }
        });

        r2.setText("Refuse");
        r2.setActionCommand("Refuse");
        r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2ActionPerformed(evt);
            }
        });

        r1.setText("Accepte");
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });

        tab_conge.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id", "Demandeur", "debut", "Durée", "type", "Etat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tab_conge.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_congeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab_conge);

        modifier.setText("modifier");
        modifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifierMouseClicked(evt);
            }
        });
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });

        button1.setActionCommand("X");
        button1.setLabel("X");
        button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button1MouseClicked(evt);
            }
        });
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        ajouter.setText("ajouter");
        ajouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajouterMouseClicked(evt);
            }
        });
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });

        supprimer.setText("supprimer");
        supprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supprimerMouseClicked(evt);
            }
        });

        id_cong.setText("jLabel7");

        jLabel7.setText("Jours");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)))
                    .addComponent(jLabel6))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(id_cong)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(235, 235, 235))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(zt_deb)
                                    .addComponent(comb1, 0, 286, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(zt_duree, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(r2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(57, 57, 57)
                                    .addComponent(r1)
                                    .addGap(50, 50, 50)))
                            .addComponent(demandeur, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ajouter)
                        .addComponent(modifier)
                        .addComponent(supprimer))
                    .addComponent(id_cong))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(demandeur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(zt_duree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(zt_deb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(comb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(r2)
                                .addComponent(r1)))))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jMenu1.setText("Opérations");

        jMenuItem1.setText("gestion des conges");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Gestion des employes");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Deconnexion");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGap(399, 399, 399)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
new conge().setVisible(true);
this.hide();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    new emloyee().setVisible(true);
this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
new authentification().setVisible(true);
this.setVisible(false);
this.hide();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void zt_debActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zt_debActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zt_debActionPerformed

    private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r2ActionPerformed

    private void ajouterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajouterMouseClicked
        // TODO add your handling code here:
try{
int duree =Integer.parseInt(zt_duree.getText());
String debut = zt_deb.getText();
String radio1 = r1.getText();
String radio2 = r2.getText();
String nom= demandeur.getSelectedItem().toString();
int idemp=recupid(nom);
String type= comb1.getSelectedItem().toString();

if(r1.isSelected()){
CongeImplement n = new CongeImplement () {};

Conges g = new Conges(duree,idemp,debut,type,"accepte");
n.ajouterConge(g);
cancel();
afficher();
} 
else {
if (r2.isSelected()){
CongeImplement n = new CongeImplement () {};

Conges g = new Conges(duree,idemp,debut,type, "refuse");
n.ajouterConge(g);
cancel();
afficher();
}
}

}
catch (Exception ex){
System.out.println("exception"+ex);
}



    }//GEN-LAST:event_ajouterMouseClicked

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ajouterActionPerformed

    private void modifierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifierMouseClicked
        // TODO add your handling code here:
try{
int duree =Integer.parseInt(zt_duree.getText());
int id = Integer.parseInt(id_cong.getText());
String debut = zt_deb.getText();
//String radio1 = r1.getText();
//String radio2 = r2.getText();
String nom= demandeur.getSelectedItem().toString();
int idemp=recupid(nom);
System.out.println(idemp);
String type= comb1.getSelectedItem().toString();

if(r1.isSelected()){
CongeImplement n = new CongeImplement () {};

Conges g = new Conges(id,duree,idemp,debut,type,"accepte");
n.updateConge(g);
cancel();
afficher();
} 
else {
if (r2.isSelected()){
CongeImplement n = new CongeImplement () {};

Conges g = new Conges(id,duree,idemp,debut,type, "refuse");
n.updateConge(g);
cancel();
afficher();
}
}
}
catch (Exception ex){
System.out.println("exception"+ex);
}  


    }//GEN-LAST:event_modifierMouseClicked

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modifierActionPerformed

    private void supprimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supprimerMouseClicked
        // TODO add your handling code here:
try{
String b = id_cong.getText();
//if (a==""){
//JOptionPane.showMessageDialog(null , "champ salaire est obligatoire !");
//}
int id =Integer.parseInt(b);
CongeImplement n = new CongeImplement() {};
n.deleteConge( id );
cancel();
afficher();

}
catch (Exception ex){
System.out.println("exception"+ex);
}

    }//GEN-LAST:event_supprimerMouseClicked

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_button1ActionPerformed

    private void tab_congeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_congeMouseClicked
        // TODO add your handling code here:
//"id","demandeur","debut","duree","type","etat"
String id =tab_conge.getValueAt(tab_conge.getSelectedRow(), 0).toString();
id_cong.setText(id);
String debut=tab_conge.getValueAt(tab_conge.getSelectedRow(),2 ).toString();
zt_deb.setText(debut);
String duree = tab_conge.getValueAt(tab_conge.getSelectedRow(), 3).toString();
zt_duree.setText(duree);
String etat=tab_conge.getValueAt(tab_conge.getSelectedRow(), 5).toString();
if (etat=="accepte"){
r2.setSelected(true);
}else
{
r1.setSelected(true);
}
ajouter.setEnabled(false);
modifier.setEnabled(true);
supprimer.setEnabled(true);

    }//GEN-LAST:event_tab_congeMouseClicked

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r1ActionPerformed

    private void button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseClicked
        // TODO add your handling code here:
cancel();
    }//GEN-LAST:event_button1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(conge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(conge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(conge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(conge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new conge().setVisible(true);
            }
        });
    }

public void cancel(){

id_cong.setText("");
zt_duree.setText("");
zt_deb.setText("");
r1.setSelected(false);
r2.setSelected(false);
ajouter.setEnabled(true);
modifier.setEnabled(false);
supprimer.setEnabled(false);
}

public void remplircombo (){
try{
Connect cx = new Connect();
String sql = "SELECT id , nom FROM `employee`";
PreparedStatement statement = cx.conn.prepareStatement(sql);
ResultSet rs= statement.executeQuery();
int i=0;
while(rs.next())
{
String nom= rs.getString("nom");
//int id= rs.getInt("id");
 demandeur.addItem(nom);
i++;
}
}
catch (SQLException ex) {
System.out.println("exception"+ex);
}
}

public int recupid(String nom) {
try{
Connect cx = new Connect();
String sql = "SELECT id FROM `employee` where nom= '"+nom+"' ";
PreparedStatement statement = cx.conn.prepareStatement(sql);
ResultSet rs= statement.executeQuery();
if (rs.next()){
return rs.getInt("id");}
}
catch(SQLException ex) {
System.out.println("exception"+ex);
}    return 0;
}

public String recupnom(int id) {
try{
Connect cx = new Connect();
String sql = "SELECT nom FROM `employee` where id= ?";
PreparedStatement statement = cx.conn.prepareStatement(sql);
statement.setInt(1,id);
ResultSet rs= statement.executeQuery();

return rs.getString("nom");
}
catch(SQLException ex) {
System.out.println("exception"+ex);
}    return "";
}
public void afficher (){
try{
String columns [] = {"id","demandeur","debut","duree","type","etat"};
String data[][] = new String[20][10];

Connect cx = new Connect();

String sql = "SELECT * FROM `conge` ";
PreparedStatement statement = cx.conn.prepareStatement(sql);
ResultSet rs= statement.executeQuery();
int i=0;
while(rs.next())
{
//nom, email, mdp, adresse, grade, telephone, salaire
int id =rs.getInt("id");
String etat= rs.getString("etat");
String debut= rs.getString("debut");
int duree= rs.getInt("duree");
String type= rs.getString("type");
int demandeur = rs.getInt("demandeur");

String sql1 = "SELECT nom FROM `employee` where id = '"+demandeur+"' ";
PreparedStatement statement1 = cx.conn.prepareStatement(sql1);
ResultSet rs1= statement1.executeQuery();  
if (rs1.next()){
String nom = rs1.getString("nom");
data[i][0]= id+"";
data[i][1]= nom;
data[i][2]= debut;
data[i][3]= duree+"";
data[i][4]= type;
data[i][5]= etat;

}
i++;
}
DefaultTableModel model = new DefaultTableModel(data,columns);
tab_conge.setModel(model);
}
catch (SQLException ex) {
System.out.println("exception"+ex);
}
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouter;
    private java.awt.Button button1;
    private javax.swing.JComboBox<String> comb1;
    private javax.swing.JComboBox<String> demandeur;
    private javax.swing.JLabel id_cong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modifier;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JButton supprimer;
    private javax.swing.JTable tab_conge;
    private javax.swing.JTextField zt_deb;
    private javax.swing.JTextField zt_duree;
    // End of variables declaration//GEN-END:variables
}
