/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import implementation.Connect;
import java.awt.event.MouseEvent;
import static java.nio.file.Files.list;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import static java.util.Collections.list;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import implementation.EmployeeImplement;
import model.employee;

/**
 *
 * @author Hedia
 */
public class emloyee extends javax.swing.JFrame {

    /**
     * Creates new form emloyee
     */
    public emloyee() {
        initComponents();
afficher();
modifier.setEnabled(false);
supprimer.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        zt_nom = new javax.swing.JTextField();
        zt_email = new javax.swing.JTextField();
        zt_pass = new javax.swing.JTextField();
        zt_grade = new javax.swing.JTextField();
        zt_telephone = new javax.swing.JTextField();
        zt_sal = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        zt_adress = new javax.swing.JTextArea();
        ajouter = new javax.swing.JButton();
        modifier = new javax.swing.JButton();
        supprimer = new javax.swing.JButton();
        id_emp = new java.awt.Label();
        button1 = new java.awt.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_emp = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("gestion des employes");

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Gestion des employes");

        jLabel2.setText("Nom                     : ");

        jLabel3.setText("Email                    :");

        jLabel4.setText("Password             :");

        jLabel5.setText("Adresse                :");

        jLabel6.setText("Grade                    :");

        jLabel7.setText("téléphone              :");

        jLabel8.setText("Salaire                    :");

        zt_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zt_nomActionPerformed(evt);
            }
        });

        zt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zt_emailActionPerformed(evt);
            }
        });

        zt_adress.setColumns(20);
        zt_adress.setRows(5);
        jScrollPane2.setViewportView(zt_adress);

        ajouter.setText("ajouter");
        ajouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajouterMouseClicked(evt);
            }
        });
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });

        modifier.setText("modifier");
        modifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifierMouseClicked(evt);
            }
        });
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });

        supprimer.setText("supprimer");
        supprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supprimerMouseClicked(evt);
            }
        });

        id_emp.setEnabled(false);
        id_emp.setName(""); // NOI18N
        id_emp.setText("label3");
        id_emp.setVisible(false);

        button1.setActionCommand("X");
        button1.setLabel("X");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        tab_emp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nom", "Email", "Password", "Adresse", "Grade", "Téléphone", "Salaire"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tab_emp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_empMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab_emp);
        if (tab_emp.getColumnModel().getColumnCount() > 0) {
            tab_emp.getColumnModel().getColumn(0).setHeaderValue("Id");
        }

        jMenu1.setText("Opértions");

        jMenuItem1.setText("Gestion des conger");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Gestion des employes");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Deconnexion");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                                .addComponent(zt_sal, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(zt_telephone, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(zt_pass, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(zt_email, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(zt_nom, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(zt_grade))))
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(320, 320, 320)
                        .addComponent(id_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                        .addComponent(ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(173, 173, 173))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ajouter)
                                .addComponent(modifier)
                                .addComponent(supprimer)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel6)
                                            .addComponent(zt_grade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(36, 36, 36)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7)
                                            .addComponent(zt_telephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel8)
                                            .addComponent(zt_sal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(id_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(74, 74, 74))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(zt_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(zt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(zt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(280, 280, 280)))
                .addContainerGap(431, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void zt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zt_emailActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
      new conge().setVisible(true);    
this.setVisible(false);
this.hide();
     // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
 
this.setVisible(true); 

 
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
   new authentification().setVisible(true);   

this.hide();  

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ajouterActionPerformed

    private void tab_empMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_empMouseClicked
        // TODO add your handling code here:
//modifier_employe me = new modifier_employe();
String id=tab_emp.getValueAt(tab_emp.getSelectedRow(), 0).toString();
id_emp.setText(id);

//me.zt_nom.setText(id);
String nom=tab_emp.getValueAt(tab_emp.getSelectedRow(), 1).toString();
zt_nom.setText(nom);
zt_nom.setEnabled(false);
String mail=tab_emp.getValueAt(tab_emp.getSelectedRow(), 2).toString();
zt_email.setText(mail);
zt_email.setEnabled(false);
String pass=tab_emp.getValueAt(tab_emp.getSelectedRow(), 3).toString();
zt_pass.setText(pass);
zt_pass.setEnabled(false);
String add=tab_emp.getValueAt(tab_emp.getSelectedRow(), 4).toString();
zt_adress.setText(add);
zt_adress.setEnabled(false);
String grade=tab_emp.getValueAt(tab_emp.getSelectedRow(), 5).toString();
zt_grade.setText(grade);
zt_grade.setEnabled(false);
String tel=tab_emp.getValueAt(tab_emp.getSelectedRow(), 6).toString();
zt_telephone.setText(tel);
zt_telephone.setEnabled(false);
String sal=tab_emp.getValueAt(tab_emp.getSelectedRow(), 7).toString();
zt_sal.setText(sal);
ajouter.setEnabled(false);
modifier.setEnabled(true);
supprimer.setEnabled(true);
    }//GEN-LAST:event_tab_empMouseClicked

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
cancel();
    }//GEN-LAST:event_button1ActionPerformed

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_modifierActionPerformed

    private void modifierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifierMouseClicked
        // TODO add your handling code here:
try{
String a = zt_sal.getText();
String b = id_emp.getText();
//if (a==""){
//JOptionPane.showMessageDialog(null , "champ salaire est obligatoire !");
//}

double sal = Double.parseDouble(a);
int id =Integer.parseInt(b);
EmployeeImplement n = new EmployeeImplement() {};
n.updateSalaire( id , sal);
cancel();
afficher();

}
catch (Exception ex){
System.out.println("exception"+ex);
}
    }//GEN-LAST:event_modifierMouseClicked

    private void supprimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supprimerMouseClicked
        // TODO add your handling code here:

try{
String b = id_emp.getText();
//if (a==""){
//JOptionPane.showMessageDialog(null , "champ salaire est obligatoire !");
//}
int id =Integer.parseInt(b);
EmployeeImplement n = new EmployeeImplement() {};
n.SupprimerEmployee( id );
cancel();
afficher();

}
catch (Exception ex){
System.out.println("exception"+ex);
}


    }//GEN-LAST:event_supprimerMouseClicked

    private void ajouterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajouterMouseClicked
        // TODO add your handling code here:

try{
String nom = zt_nom.getText();
String email = zt_email.getText();
String passwd = zt_pass.getText();
String adresse = zt_adress.getText();
String grade = zt_grade.getText();
String tele = zt_telephone.getText();
double sal = Double.parseDouble(zt_sal.getText()) ;

//if (a==""){
//JOptionPane.showMessageDialog(null , "champ salaire est obligatoire !");
//}
employee e = new employee( nom, email,  passwd,adresse, grade,  tele ,sal);

EmployeeImplement n = new EmployeeImplement() {};
n.ajoutEmployee(e);
afficher();
cancel1();
afficher();

}
catch (Exception ex){
System.out.println("exception"+ex);
}

    }//GEN-LAST:event_ajouterMouseClicked

    private void zt_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zt_nomActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_zt_nomActionPerformed
void cancel(){

id_emp.setText("");

//me.zt_nom.setText(id);

zt_nom.setText("");
zt_nom.setEnabled(true);

zt_email.setText("");
zt_email.setEnabled(true);
String pass=tab_emp.getValueAt(tab_emp.getSelectedRow(), 3).toString();
zt_pass.setText("");
zt_pass.setEnabled(true);
String add=tab_emp.getValueAt(tab_emp.getSelectedRow(), 4).toString();
zt_adress.setText("");
zt_adress.setEnabled(true);
String grade=tab_emp.getValueAt(tab_emp.getSelectedRow(), 5).toString();
zt_grade.setText("");
zt_grade.setEnabled(true);
String tel=tab_emp.getValueAt(tab_emp.getSelectedRow(), 6).toString();
zt_telephone.setEnabled(true);
zt_telephone.setText("");
String sal=tab_emp.getValueAt(tab_emp.getSelectedRow(), 7).toString();
zt_sal.setText("");
ajouter.setEnabled(true);
modifier.setEnabled(false);
supprimer.setEnabled(false);
}

void cancel1(){

id_emp.setText("");

//me.zt_nom.setText(id);

zt_nom.setText("");
zt_nom.setEnabled(true);
zt_email.setText("");
zt_email.setEnabled(true);

zt_pass.setText("");
zt_pass.setEnabled(true);

zt_adress.setText("");
zt_adress.setEnabled(true);

zt_grade.setText("");
zt_grade.setEnabled(true);

zt_telephone.setEnabled(true);
zt_telephone.setText("");

zt_sal.setText("");
}



// affichage dans le tableau 
 public void afficher (){
try{
String columns [] = {"id","nom","email","password","adresse","grade", "telephone","salaire"};
String data[][] = new String[20][10];

Connect cx = new Connect();
String sql = "SELECT * FROM `employee`";
PreparedStatement statement = cx.conn.prepareStatement(sql);
ResultSet rs= statement.executeQuery();
int i=0;
while(rs.next())
{
//nom, email, mdp, adresse, grade, telephone, salaire
int id =rs.getInt("id");
String nom= rs.getString("nom");
String email= rs.getString("email");
String mdp= rs.getString("mdp");
String adresse= rs.getString("adresse");
String grade= rs.getString("grade");
String telephone= rs.getString("telephone");
double salaire = rs.getDouble("salaire");

data[i][0]= id+"";
data[i][1]= nom;
data[i][2]= email;
data[i][3]= mdp;
data[i][4]= adresse;
data[i][5]= grade;
data[i][6]= telephone;
data[i][7] = salaire+"";

i++;
}
DefaultTableModel model = new DefaultTableModel(data,columns);
tab_emp.setModel(model);
}
catch (SQLException ex) {
System.out.println("exception"+ex);
}
}



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(emloyee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(emloyee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(emloyee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(emloyee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new emloyee().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouter;
    private java.awt.Button button1;
    private java.awt.Label id_emp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton modifier;
    private javax.swing.JButton supprimer;
    private javax.swing.JTable tab_emp;
    private javax.swing.JTextArea zt_adress;
    private javax.swing.JTextField zt_email;
    private javax.swing.JTextField zt_grade;
    private javax.swing.JTextField zt_nom;
    private javax.swing.JTextField zt_pass;
    private javax.swing.JTextField zt_sal;
    private javax.swing.JTextField zt_telephone;
    // End of variables declaration//GEN-END:variables
}
